name: Docker Multi-Arch Build and Push

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    tags:
      - 'v*.*.*' # Trigger on new tags like v1.0.0
  pull_request:
    branches:
      - main # Optional: Trigger on PRs to main for build testing

env:
  # Your Docker Hub username and repository name
  DOCKER_REPOSITORY: davy39/mayara-signalk-radar # e.g., myuser/my-node-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Required for OIDC login to GitHub Container Registry, not strictly needed for Docker Hub
      # if you're using DOCKER_USERNAME/DOCKER_PASSWORD
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Build and push Docker image (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile ('.' means current directory)
          file: ./Dockerfile # Path to your Dockerfile if not named 'Dockerfile'
          platforms: linux/amd64,linux/arm64 # The architectures to build for
          push: true # Push the image to Docker Hub
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Store build cache in GitHub Actions cache
